### ISSUE TITLE
Out of memory in validation step

### ISSUE THREAD

**Issue by sausax** [facebookresearch/loop#57]
There is a sharp jump in GPU memory usage in validation step 
```
+-------------------------------+----------------------+----------------------+
--
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 58%   70C    P2    67W / 200W |   1906MiB /  8111MiB |     19%      Default |
+-------------------------------+----------------------+----------------------+
--
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 58%   70C    P2   120W / 200W |   5202MiB /  8111MiB |     41%      Default |
+-------------------------------+----------------------+----------------------+
--
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 58%   70C    P2    67W / 200W |   8108MiB /  8111MiB |     25%      Default |
+-------------------------------+----------------------+----------------------+
```
Out of memory error 

```
Valid (loss 53.34) epoch 1:   9%|██████▍                                                                | 1/11 [00:01<00:13,  1.33s/it]THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    main()
  File "train.py", line 200, in main
    eval_loss = evaluate(model, criterion, epoch, eval_losses)
  File "train.py", line 157, in evaluate
    output, _ = model([input, spkr], target[0])
  File "/home/saurabh/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/saurabh/git_repos/loop/model.py", line 313, in forward
    out, attn = self.decoder(x, ident, context, start)
  File "/home/saurabh/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/saurabh/git_repos/loop/model.py", line 230, in forward
    self.S_t = self.update_buffer(self.S_t, c_t, o_tm1, ident)
  File "/home/saurabh/git_repos/loop/model.py", line 200, in update_buffer
    Sp = torch.cat([z_t, S_tm1[:, :, :-1]], 2)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
```

**Comment by sausax** [comment]
Fixed after adding ` with torch.no_grad():` before calling validation https://github.com/facebookresearch/loop/blob/master/train.py#L200
